### ISSUE TITLE
Feature request: node key

### ISSUE THREAD

**Issue by ltdrdata** [ali1234/comfyui-node-decorator#1]
**Request:** 
It would be beneficial to have a structure that allows avoiding conflicts in node keys with other custom nodes through prefix/postfix, while using the class name as the current node's key.

**Consideration:**
ComfyUI-Manager operates on a structure that statically scans code to extract node information. It typically scans `NODE_CLASS_MAPPINGS` using regex or allows developers to explicitly extract a list of nodes through node_list.json.
_(When using a dynamically generated key at runtime, extraction is only possible by installing and running it directly. However, configuring a proper installation environment is often not feasible, and it becomes impractical to assess the update status of hundreds of custom nodes in this manner.)_

If it doesn't adhere to a static pattern, it implies that the Manager may not provide accurate information (missing nodes, node list, ...). It would be beneficial if considerations for this aspect were taken into account.

Therefore, it would be great if the structure could be designed to accurately extract the list of node keys through static scanning.

**Comment by ali1234** [comment]
There is already a system for preventing conflicts with other packs: you call `set_pack_options` in `__init__.py` to set the pack name, and it is prefixed on every node's key, along with the revision level of that node (which is an option on the decorator, so per-node.) You get node keys like `prognodes_0_Literal` for the Literal node. Just pick a unique name.

This is not amenable to static analysis; rather, the whole point of this code is to avoid having to maintain a list of nodes and other such boilerplate. However, it would be easy to add a function to dump out a node_list.json, and add it to a pre-commit hook.

**Comment by ali1234** [comment]
Added a json generator:

```
(.venv) al@al-desktop:~/ComfyUI/custom_nodes$ python3 -m comfyui-node-decorator
{
    "prognodes_0_BinaryOp": "All binary operators from Python stdlib.",
    "prognodes_0_Format": "Performs string replacement using the standard Python format() method.",
    "prognodes_0_GetItem": "Selects a key from a collection ie a dict.",
    "prognodes_0_Join": "Joins an interable of strings into a single string.",
    "prognodes_0_Literal": "Allows defining a literal value directly in Python code.",
    "prognodes_0_MapJoin": "I can't remember what this does. :(",
    "prognodes_0_MappedBinaryOp": "Map a binary operation to an iterable.",
    "prognodes_0_MappedUnaryOp": "Map a unary operation to an iterable.",
    "prognodes_0_Print": "Prints the str() or repr() of the input.",
    "prognodes_0_Switch": "A switch that selects between the two inputs.",
    "prognodes_0_UnaryOp": "All unary operators from Python stdlib."
}
```

The output of this could just be commited to the repo if this was a real pack.

**Comment by ali1234** [comment]
And now the node keys and class names match too.

**Comment by ltdrdata** [comment]
> Added a json generator:
> 
> ```
> (.venv) al@al-desktop:~/ComfyUI/custom_nodes$ python3 -m comfyui-node-decorator
> {
>     "prognodes_0_BinaryOp": "All binary operators from Python stdlib.",
>     "prognodes_0_Format": "Performs string replacement using the standard Python format() method.",
>     "prognodes_0_GetItem": "Selects a key from a collection ie a dict.",
>     "prognodes_0_Join": "Joins an interable of strings into a single string.",
>     "prognodes_0_Literal": "Allows defining a literal value directly in Python code.",
>     "prognodes_0_MapJoin": "I can't remember what this does. :(",
>     "prognodes_0_MappedBinaryOp": "Map a binary operation to an iterable.",
>     "prognodes_0_MappedUnaryOp": "Map a unary operation to an iterable.",
>     "prognodes_0_Print": "Prints the str() or repr() of the input.",
>     "prognodes_0_Switch": "A switch that selects between the two inputs.",
>     "prognodes_0_UnaryOp": "All unary operators from Python stdlib."
> }
> ```
> 
> The output of this could just be commited to the repo if this was a real pack.

Oh, there might be functionalities in the custom node that depend on ComfyUI. In that case, wouldn't creating a .json file standalone like this be problematic?

It seems like there is an assumption that the custom node needs to be imported without fail for this to work properly.

**Comment by ali1234** [comment]
It is assumed that pack maintainers will have a ComfyUI venv for testing. The json can be generated there and committed to the repo.

**Comment by ltdrdata** [comment]
> It is assumed that pack maintainers will have a ComfyUI venv for testing. The json can be generated there and committed to the repo.

This does not refer to the meaning of the Python environment. 

It is assumed that many custom nodes are imported and executed in ComfyUI by default. Therefore, to access Comfy's functionality, you need to access Comfy's packages in the form of 'import comfy' or 'import nodes'. 

If a custom node is executed independently, it may become an unrecognized package, leading to a failed execution.

**Comment by ali1234** [comment]
That problem can be avoided by invoking it like this:

```
(.venv) al@al-desktop:~/ComfyUI$ python3 -m custom_nodes.comfyui-node-decorator
Total VRAM 7970 MB, total RAM 64230 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : native
VAE dtype: torch.float32
Using xformers cross attention
{
    "prognodes_0_BinaryOp": "All binary operators from Python stdlib.",
    "prognodes_0_Format": "Performs string replacement using the standard Python format() method.",
    "prognodes_0_GetItem": "Selects a key from a collection ie a dict.",
    "prognodes_0_Join": "Joins an interable of strings into a single string.",
    "prognodes_0_Literal": "Allows defining a literal value directly in Python code.",
    "prognodes_0_MapJoin": "I can't remember what this does. :(",
    "prognodes_0_MappedBinaryOp": "Map a binary operation to an iterable.",
    "prognodes_0_MappedUnaryOp": "Map a unary operation to an iterable.",
    "prognodes_0_Print": "Prints the str() or repr() of the input.",
    "prognodes_0_Switch": "A switch that selects between the two inputs.",
    "prognodes_0_UnaryOp": "All unary operators from Python stdlib."
}
```

This isn't suitable for redirecting to a file due to the extra output from comfy, so I made it write directly to the node_list.json instead.
